# Generated by Django 6.0.8 on 2026-09-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_replace_prototype_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='navigation',
            field=models.JSONField(default=list),
        ),
    ]
