# Generated by Django 6.0.8 on 2026-09-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_site_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_widget',
            field=models.JSONField(default=dict),
        ),
    ]
