# Generated by Django 6.0.8 on 2026-10-01 18:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_whatsapp_widget'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('is_sample', models.BooleanField(default=False, help_text='Generated demo content, not information supplied by the business.')),
                ('source_note', models.CharField(blank=True, default='', max_length=300)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('template', models.CharField(choices=[('standard', 'Standard'), ('legal', 'Legal / policy'), ('contact', 'Contact')], default='standard', max_length=20)),
                ('eyebrow', models.CharField(blank=True, default='', max_length=80)),
                ('subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('sections', models.JSONField(blank=True, default=list)),
                ('contact', models.JSONField(blank=True, default=dict)),
                ('seo', models.JSONField(blank=True, null=True)),
                ('show_in_footer', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.imageasset')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
