# Generated by Django 6.0.8 on 2026-10-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_grant_page_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author_name',
            field=models.CharField(default='Clada Safari Bliss', max_length=120),
        ),
    ]
