# Generated by Django 6.0.8 on 2026-10-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageasset',
            name='source',
            field=models.CharField(choices=[('original', 'Original Clada Safari Bliss website'), ('pexels', 'Pexels'), ('upload', 'Uploaded in the dashboard'), ('other', 'Other')], db_index=True, default='other', max_length=12),
        ),
    ]
