# Generated by Django 6.0.8 on 2026-09-29 08:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_destination_source_note_tour_source_note_and_more'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('is_sample', models.BooleanField(default=False, help_text='Generated demo content, not information supplied by the business.')),
                ('source_note', models.CharField(blank=True, default='', max_length=300)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('tag', models.CharField(blank=True, default='', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.imageasset')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.travelarea')),
                ('places', models.ManyToManyField(blank=True, related_name='areas', to='catalog.place')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='tours', to='catalog.travelarea'),
        ),
    ]
