# Generated by Django 6.0.8 on 2026-10-01 18:48

import django_countries.fields
from django.db import migrations, models


def backfill_codes(apps, schema_editor):
    """Rows saved before codes were required get theirs from the country name."""
    from django_countries import countries

    Country = apps.get_model('catalog', 'Country')
    for row in Country.objects.all():
        code = (row.iso_code or '').upper() or countries.by_name(row.name)
        if not code:
            raise RuntimeError(f'Set an ISO code for "{row.name}" in Django admin before migrating.')
        if code != row.iso_code:
            row.iso_code = code
            row.save(update_fields=['iso_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_travel_areas'),
    ]

    operations = [
        migrations.RunPython(backfill_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=django_countries.fields.CountryField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(choices=[('east-africa', 'East Africa'), ('europe', 'Europe'), ('africa', 'Africa'), ('middle-east', 'Middle East'), ('asia', 'Asia'), ('americas', 'Americas'), ('oceania', 'Oceania'), ('other', 'Elsewhere')], db_index=True, max_length=20),
        ),
    ]
