# Generated by Django 6.0.8 on 2026-10-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_country_iso_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price_basis',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
