# Generated by Django 6.0.8 on 2026-10-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_tour_price_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='group_size_max',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
